# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d008854352a405d240527b981a84c2be1aa682fb2c4fb955041f89fc1d84606c86b337bab2cda364931bbe683710584c1f8524ab59bfb3653246615565834d
  API_KEY_SUNLIGHTFOUNDATION: <%= ENV["API_KEY_SUNLIGHTFOUNDATION"] %>


test:
  secret_key_base: fcd957bf666d4a3a7f76873342bc09151b2e84b9b0e39686577ad48324039c5b1b12eed0b96deee3e9d86bec5855690c579e0019756f848228eaf8ecc537cc81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  API_KEY_SUNLIGHTFOUNDATION: <%= ENV["API_KEY_SUNLIGHTFOUNDATION"] %>
